// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protomodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendSingleTextMsgC2S struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSingleTextMsgC2S) Reset()         { *m = SendSingleTextMsgC2S{} }
func (m *SendSingleTextMsgC2S) String() string { return proto.CompactTextString(m) }
func (*SendSingleTextMsgC2S) ProtoMessage()    {}
func (*SendSingleTextMsgC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_95a8b945d75bbc6e, []int{0}
}
func (m *SendSingleTextMsgC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSingleTextMsgC2S.Unmarshal(m, b)
}
func (m *SendSingleTextMsgC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSingleTextMsgC2S.Marshal(b, m, deterministic)
}
func (dst *SendSingleTextMsgC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSingleTextMsgC2S.Merge(dst, src)
}
func (m *SendSingleTextMsgC2S) XXX_Size() int {
	return xxx_messageInfo_SendSingleTextMsgC2S.Size(m)
}
func (m *SendSingleTextMsgC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSingleTextMsgC2S.DiscardUnknown(m)
}

var xxx_messageInfo_SendSingleTextMsgC2S proto.InternalMessageInfo

func (m *SendSingleTextMsgC2S) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SendSingleTextMsgC2S) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendSingleTextMsgS2C struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSingleTextMsgS2C) Reset()         { *m = SendSingleTextMsgS2C{} }
func (m *SendSingleTextMsgS2C) String() string { return proto.CompactTextString(m) }
func (*SendSingleTextMsgS2C) ProtoMessage()    {}
func (*SendSingleTextMsgS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_95a8b945d75bbc6e, []int{1}
}
func (m *SendSingleTextMsgS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSingleTextMsgS2C.Unmarshal(m, b)
}
func (m *SendSingleTextMsgS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSingleTextMsgS2C.Marshal(b, m, deterministic)
}
func (dst *SendSingleTextMsgS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSingleTextMsgS2C.Merge(dst, src)
}
func (m *SendSingleTextMsgS2C) XXX_Size() int {
	return xxx_messageInfo_SendSingleTextMsgS2C.Size(m)
}
func (m *SendSingleTextMsgS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSingleTextMsgS2C.DiscardUnknown(m)
}

var xxx_messageInfo_SendSingleTextMsgS2C proto.InternalMessageInfo

func (m *SendSingleTextMsgS2C) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

type SendSinglePublishTextMsgS2C struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSinglePublishTextMsgS2C) Reset()         { *m = SendSinglePublishTextMsgS2C{} }
func (m *SendSinglePublishTextMsgS2C) String() string { return proto.CompactTextString(m) }
func (*SendSinglePublishTextMsgS2C) ProtoMessage()    {}
func (*SendSinglePublishTextMsgS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_95a8b945d75bbc6e, []int{2}
}
func (m *SendSinglePublishTextMsgS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSinglePublishTextMsgS2C.Unmarshal(m, b)
}
func (m *SendSinglePublishTextMsgS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSinglePublishTextMsgS2C.Marshal(b, m, deterministic)
}
func (dst *SendSinglePublishTextMsgS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSinglePublishTextMsgS2C.Merge(dst, src)
}
func (m *SendSinglePublishTextMsgS2C) XXX_Size() int {
	return xxx_messageInfo_SendSinglePublishTextMsgS2C.Size(m)
}
func (m *SendSinglePublishTextMsgS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSinglePublishTextMsgS2C.DiscardUnknown(m)
}

var xxx_messageInfo_SendSinglePublishTextMsgS2C proto.InternalMessageInfo

func (m *SendSinglePublishTextMsgS2C) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SendSinglePublishTextMsgS2C) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendSinglePublishTextMsgC2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSinglePublishTextMsgC2S) Reset()         { *m = SendSinglePublishTextMsgC2S{} }
func (m *SendSinglePublishTextMsgC2S) String() string { return proto.CompactTextString(m) }
func (*SendSinglePublishTextMsgC2S) ProtoMessage()    {}
func (*SendSinglePublishTextMsgC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_95a8b945d75bbc6e, []int{3}
}
func (m *SendSinglePublishTextMsgC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSinglePublishTextMsgC2S.Unmarshal(m, b)
}
func (m *SendSinglePublishTextMsgC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSinglePublishTextMsgC2S.Marshal(b, m, deterministic)
}
func (dst *SendSinglePublishTextMsgC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSinglePublishTextMsgC2S.Merge(dst, src)
}
func (m *SendSinglePublishTextMsgC2S) XXX_Size() int {
	return xxx_messageInfo_SendSinglePublishTextMsgC2S.Size(m)
}
func (m *SendSinglePublishTextMsgC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSinglePublishTextMsgC2S.DiscardUnknown(m)
}

var xxx_messageInfo_SendSinglePublishTextMsgC2S proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendSingleTextMsgC2S)(nil), "protomodel.SendSingleTextMsgC2S")
	proto.RegisterType((*SendSingleTextMsgS2C)(nil), "protomodel.SendSingleTextMsgS2C")
	proto.RegisterType((*SendSinglePublishTextMsgS2C)(nil), "protomodel.SendSinglePublishTextMsgS2C")
	proto.RegisterType((*SendSinglePublishTextMsgC2S)(nil), "protomodel.SendSinglePublishTextMsgC2S")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_95a8b945d75bbc6e) }

var fileDescriptor_message_95a8b945d75bbc6e = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0xb9, 0xf9, 0x29,
	0xa9, 0x39, 0x4a, 0x4e, 0x5c, 0x22, 0xc1, 0xa9, 0x79, 0x29, 0xc1, 0x99, 0x79, 0xe9, 0x39, 0xa9,
	0x21, 0xa9, 0x15, 0x25, 0xbe, 0xc5, 0xe9, 0xce, 0x46, 0xc1, 0x42, 0x02, 0x5c, 0xcc, 0xa5, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x20, 0xa6, 0x90, 0x04, 0x17, 0x3b, 0xd4, 0x18,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x49, 0x0b, 0x8b, 0x19, 0xc1, 0x46, 0xce,
	0x42, 0x42, 0x5c, 0x2c, 0x69, 0x39, 0x89, 0xe9, 0x60, 0x43, 0x38, 0x82, 0xc0, 0x6c, 0x25, 0x4f,
	0x2e, 0x69, 0x84, 0xda, 0x80, 0xd2, 0xa4, 0x9c, 0xcc, 0xe2, 0x0c, 0x24, 0x2d, 0xa4, 0x58, 0x2b,
	0x8b, 0xdb, 0x28, 0x67, 0xa3, 0xe0, 0x24, 0x36, 0xb0, 0x2f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x30, 0xb1, 0x6c, 0xdb, 0xfd, 0x00, 0x00, 0x00,
}
