// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping.proto

package protomodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingS2C struct {
	TimeStamp            int64    `protobuf:"varint,1,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingS2C) Reset()         { *m = PingS2C{} }
func (m *PingS2C) String() string { return proto.CompactTextString(m) }
func (*PingS2C) ProtoMessage()    {}
func (*PingS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_ping_f045b84966a15786, []int{0}
}
func (m *PingS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingS2C.Unmarshal(m, b)
}
func (m *PingS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingS2C.Marshal(b, m, deterministic)
}
func (dst *PingS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingS2C.Merge(dst, src)
}
func (m *PingS2C) XXX_Size() int {
	return xxx_messageInfo_PingS2C.Size(m)
}
func (m *PingS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PingS2C.DiscardUnknown(m)
}

var xxx_messageInfo_PingS2C proto.InternalMessageInfo

func (m *PingS2C) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type PingC2S struct {
	TimeStamp            int64    `protobuf:"varint,1,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingC2S) Reset()         { *m = PingC2S{} }
func (m *PingC2S) String() string { return proto.CompactTextString(m) }
func (*PingC2S) ProtoMessage()    {}
func (*PingC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_ping_f045b84966a15786, []int{1}
}
func (m *PingC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingC2S.Unmarshal(m, b)
}
func (m *PingC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingC2S.Marshal(b, m, deterministic)
}
func (dst *PingC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingC2S.Merge(dst, src)
}
func (m *PingC2S) XXX_Size() int {
	return xxx_messageInfo_PingC2S.Size(m)
}
func (m *PingC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PingC2S.DiscardUnknown(m)
}

var xxx_messageInfo_PingC2S proto.InternalMessageInfo

func (m *PingC2S) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func init() {
	proto.RegisterType((*PingS2C)(nil), "protomodel.PingS2C")
	proto.RegisterType((*PingC2S)(nil), "protomodel.PingC2S")
}

func init() { proto.RegisterFile("ping.proto", fileDescriptor_ping_f045b84966a15786) }

var fileDescriptor_ping_f045b84966a15786 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xcc, 0x4b,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0xb9, 0xf9, 0x29, 0xa9, 0x39, 0x4a,
	0x1a, 0x5c, 0xec, 0x01, 0x99, 0x79, 0xe9, 0xc1, 0x46, 0xce, 0x42, 0xb2, 0x5c, 0x5c, 0x25, 0x99,
	0xb9, 0xa9, 0xf1, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x9c,
	0x20, 0x91, 0x60, 0x90, 0x00, 0x4c, 0xa5, 0xb3, 0x51, 0x30, 0x01, 0x95, 0x49, 0x6c, 0x60, 0xf3,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x22, 0x30, 0x37, 0x74, 0x00, 0x00, 0x00,
}
